"""add organization relationships

Revision ID: a8259e2a5973
Revises: 1aeb6ead55f9
Create Date: 2026-07-29 16:47:16.546842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8259e2a5973'
down_revision: Union[str, Sequence[str], None] = '1aeb6ead55f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('organizations_slug_key'), 'organizations', type_='unique')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.add_column('projects', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'projects', 'organizations', ['organization_id'], ['id'])
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'organization_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'organization_id')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_unique_constraint(op.f('organizations_slug_key'), 'organizations', ['slug'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
