"""link tasks to alerts

Revision ID: ed02ec83e267
Revises: bc2a23584b06
Create Date: 2026-09-30 01:45:19.236938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed02ec83e267'
down_revision: Union[str, Sequence[str], None] = 'bc2a23584b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('alert_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_alert_id'), 'tasks', ['alert_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'alerts', ['alert_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_alert_id'), table_name='tasks')
    op.drop_column('tasks', 'alert_id')
    # ### end Alembic commands ###
