"""add device telemetry table

Revision ID: ee5ebae3e8ce
Revises: 74fa59b728b5
Create Date: 2026-08-26 14:37:16.291994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee5ebae3e8ce'
down_revision: Union[str, Sequence[str], None] = '74fa59b728b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('sensor_1', sa.Float(), nullable=True),
    sa.Column('sensor_2', sa.Float(), nullable=True),
    sa.Column('sensor_3', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_telemetry_device_id'), 'device_telemetry', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_telemetry_id'), 'device_telemetry', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_telemetry_id'), table_name='device_telemetry')
    op.drop_index(op.f('ix_device_telemetry_device_id'), table_name='device_telemetry')
    op.drop_table('device_telemetry')
    # ### end Alembic commands ###
